export const PRODUCT_SERVICE = '/product-service/api/v1'
export const ORDER_SERVICE = '/order-service/api/v1'
export const PAYMENT_SERVICE = '/payment-service/api/v1'
export const USER_SERVICE = '/user-service/api/v1'
export const FORUM_SERVICE = '/forum-service/api/v1'
export const MESSAGE_SERVICE = '/message-service/api/v1'
