import { Metadata } from 'next'

import Banner from '@/common/banner'
import Footer from '@/common/footer'
import Header from '@/common/header'

import { siteConfig } from '@/config/site'

export const metadata: Metadata = {
  title: {
    default: siteConfig.name,
    template: `%s - ${siteConfig.subName}`,
  },
  description: 'Generated by create next app',
  icons: '/common/icon.png',
}

export default function MainLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Banner />
      <>
        <Header />
        {children}
        <Footer />
      </>
    </>
  )
}
