import type { Metadata } from 'next'

import './../src/styles/globals.css'
import dynamic from 'next/dynamic'

import { siteConfig } from '@/config/site'

export const metadata: Metadata = {
  title: {
    default: siteConfig.name,
    template: `%s - ${siteConfig.subName}`,
  },
  description: 'Generated by create next app',
  icons: '/common/icon.png',
}

const Gallery = dynamic(() => import('@/components/carousel'), {
  ssr: false,
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="scroll-smooth font-sans antialiased">
        {children}
        <Gallery />
      </body>
    </html>
  )
}
